- _drafts/Precise.md
After an optimization flag was set, it is now only 40 MB
> Update size of precise download

- _pages/portuguese.md
language support with #8 in mind, using portuguese as an example
> portuguese language support

- _pages/audio-troubleshooting.md
- _pages/troubleshooting.md
> Add basic audio ts

- _pages/german.md
some minor corrections regarding language
consistency 'du/Sie/wir' -> maybe everything should be changed to 'du', but for now it's 'Sie'
> language improvements

- _pages/automatic-testing.md
Add information about
- expect_dialog
- expect_data
> Add details about additional skill test features

- _pages/automatic-testing.md
- _pages/skills-acceptance-process.md
These are changes to some documentation based on the Skills Management Team meeting on 31 May.
> Update with info from Skills Management Team meeting 31 May

- _pages/msk.md
The main change is making sure that the venv activation is conditioned only if the github clone install of mycroft is used.
> Possibly more clear venv usage.

- _pages/configuring-nice-functions.md
Relate to mycroft-core PR https://github.com/MycroftAI/mycroft-core/pull/1635
> Added documentation for mycroft-core PR feature/nice_date

- _pages/audio-troubleshooting.md
> Fix command to change audio source

- _pages/automatic-testing.md
- _pages/message-bus.md
- _pages/skill-settings.md
Just added parentheses to print statements.
> Updated python sample code to python 3

- _pages/common-issues-in-skills-development.md
Caused me some trouble early on.
EDIT: CLA Signed
> Added warning about normalize removing "the"

- _pages/linux.md
Issue 1771 may cause some confusion, added a note about it.
> issue 1771

- _pages/mycroft-conf.md
- _pages/troubleshooting.md
mycroft-core moved location of the mycroft web config cache
https://github.com/MycroftAI/mycroft-core/commit/b0b88bbd621ed269750c2886f9956c1685a72fdf
> Replace references to /opt/mycroft/web_config_cache.json

- _pages/picroft.md
Pi3 B+ -> Supported
Jessie Lite to -> Stretch Lite
> Update Information regarding the Picroft image

- _pages/skill-submission.md
Removed the no longer used step of modifying the README.md of the Mycroft Skills Repo
and updated the text of the PR template from latest changes
> Remove step - Modify Mycroft Skills Repo README.md

- _pages/picroft.md
Hi!
I believe this was left unchanged accidentally :)
> Update Debian version in picroft.md

- _pages/languages.md
Removed the info about google cloud TTS as I understand from Åke, that this wassnt right. Only module google is working.
> aded info about google_cloud json data and how to obtain that.

- _pages/padatious.md
Nested parenthesis are now supported, updated doc to reflect this.
> Correct documentation on nested parenthesis

- _pages/mycroft-for-macos-and-windows-with-virtualbox.md
Clipboard and shared folders have been a pain to get setup for me so far. So I like running headless and using SSH. I think it is a convenient option for development so added instructions.
> Add SSH setup section

- _pages/msk.md
Just want to be sure you don't wind up with a newbie coder running `msk update ..` by mistake!
> Change confusing punctuation in msk.md

- docs/about-mycroft-ai/why-use-mycroft.md
- docs/skill-development/marketplace-submission/skill-readme-md.md
The link to the privacy policy in "Why use Mycroft?" was broken.
Copyedited skill-readme-md.md
> fix broken link to priv. pol/clean skill-readme-md

- docs/skill-development/introduction.md
Used to do this sort of thing in high school and college. It was kinda fun.
> red pen skill-development/introduction.md

- docs/mycroft-technologies/adapt/README.md
This would match the LICENCE.md info in the Adapt repo.
> Change adapt licencse info to apache v2.0

- docs/using-mycroft-ai/troubleshooting/general-troubleshooting.md
Spawned from https://github.com/MycroftAI/mycroft-core/issues/2426
> Troubleshooting Linux: Add section on AttributeError 'get_wch'

- docs/mycroft-technologies/overview.md
Remove choices that are no longer available on home.mycroft.ai and add mention to the mimic2 engine
> Update tts selection information

- docs/mycroft-technologies/overview.md
The link pointed to the retired old msm script repo.
> Update msm link to new repository

- docs/mycroft-technologies/mycroft-core/message-types.md
I think folder isnt right as what I see the data uses path to store the folderlocation
> mycroft.skills.loaded - folder is wrong - path is right

- docs/using-mycroft-ai/customizations/stt-engine.md
New documentation to reflect the update in IBM STT implementation. Code has been merged to MycroftAI/mycroft-core/dev. This documentation update should be released alongside the code change.
> Core Issue-2516 - Update documentation to match new IBM implementation

- docs/skill-development/skill-types/common-query-framework.md
The added information explains why the framework exists and walks
through a very basic query skill.
Basically the First time I create a page from scratch, let me know what I've fudged up.
> Add information of the common query framework

- docs/skill-development/skill-types/common-query-framework.md
Fix a bad block comment messing up the syntax highlighting.
> Fix syntax highlight

- docs/using-mycroft-ai/get-mycroft/picroft.md
tested this and it is working! - add to https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/picroft#tested-hardware
> add Andrea Electronics USB SUMA

- docs/skill-development/voight-kampff/test-steps.md
Adds information of the 
`Given the user's {config} is {value}`
> Documenet the configuration given VK step

- docs/using-mycroft-ai/customizations/tts-engine.md
Documentation for new Azure TTS plugin available on Pypi
Renaming legacy Microsoft TTS to Bing.
- [ X] Documentation improvements
> Update tts-engine.md to add Azure TTS

- docs/using-mycroft-ai/get-mycroft/linux.md
Modified systemd commands to be compliant with systemd systems, not just debian-based systems, as they don't have the wrapper `service`.
If your PR fits more than one category, there is a high chance you should submit more than one PR. Please consider this carefully before opening the PR.
_Either delete those that do not apply, or add an x between the square brackets like so: `- [x]`_
Yes
>  Updated systemd commands 

- docs/using-mycroft-ai/customizations/languages/german.md
Made some changes, notices and fix some errors in descriptions
> Improve German instructions and paths for other distros

- docs/using-mycroft-ai/customizations/tts-engine.md
Add notice why tts installation of coqui-ai will fail with python 3.10
> Add installation notice

- docs/using-mycroft-ai/get-mycroft/docker.md
Fix example multi line command.
- [ x] Documentation improvements
copy & paste the command
> Fix multi-line command example in docker.md
