MycroftAI/documentation

- _drafts/Language-support-in-Mycroft-8211-German.md
Don't use capitals on anchor links
Added actual german wakeword
corrected several path's
MarkDown syntax fixes
> Corrections of the German language documentation

- _pages/adapt.md
This removes the duplicate mention of commands to install Adapt via pip inside a virtualenv.
> Remove duplicate pip installation instructions - fixes #15

- _pages/skills.md
This commit does the following: 
* Changes the old Wiki links to link to the GitHub repo for each Skill
* Adds the Support and Release Skills to the Core Skills list
* Reformats the MarkDown for easier maintenance
* Adds section on pre-release Skills looking for feedback
> Change old Wiki links to GitHub repo links

- _pages/picroft-audio.md
I needed to fix the https://github.com/MycroftAI/docs-rewrite/edit/master/_pages/picroft-audio.md#L61 from `/dev/ttyAMA1` to `/dev/ttyAMA0` this should now work. This was documented in 2017 against 0.8 by myself and @btotharye. This should help picroft users.
> Update bluetooth instructions

- _pages/introduction-developing-skills.md
Based on conversations with @penrods, this covers
* how single intents work
* how multiple intents work
* how regex intents work
I'm still not 100% happy with it, but it's better than what we have. 
Assigning to @penrods for review (sorry to throw more at you)
> Better examples of using Intents with Adapt

- _pages/mimic.md
I only added it to the Ubuntu instructions -- still missing for Mac, Fedora, Arch -- as I do not know the exact package names there, and cannot verify them myself. Volunteers?
> Add PCRE library to requirements

- _pages/conversational-context.md
- The `intent_handler` and corresponding function were mismatched.
- Changed `self.milk = true` to indicate wanting milk, rather than not wanting
- Added context modification to `YesMilkIntent` handler
> Fix context example code - tea, milk and honey 

- _pages/linux.md
Since the move to python3 the virtualenv has been stored in the mycroft-core folder so the remove virtualenv step is incorrect.
> Remove reference to removing virtualenv

- _pages/picroft.md
This explains how to allow Mycroft to use the system default device instead of forcing the use of device index 0.
> Add note on USB output devices

- _pages/skill-submission.md
Changed: http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html
To: https://raw.githack.com/MycroftAI/mycroft-skills/18.08/meta_editor.html
> Update rawgit links for meta editor

- _pages/audio-troubleshooting.md
Some scripts were mislabeled as presenting inputs and outputs.
Also updated example of setting default devices to make sense in the context of previous device listing examples.
> Clarify sinks (outputs) vs sources (inputs)

- _pages/logs.md
I was trying to diagnose an error on my mark 1 and noticed that the filepaths were incorrect in the **useful diagnostic** section. Updated the paths to be the correct paths and now I get the output I was expecting (included below)
```
root@mark_1:~# cat /var/log/mycroft-skills.log | grep -i error | grep -i picker
cat: /var/log/mycroft-skills.log: No such file or directory
```
```
root@mark_1:~# tail -f /var/log/skills.log
tail: cannot open _/var/log/skills.log_ for reading: No such file or directory
tail: no files remaining
```
```
root@mark_1:~# cat /var/log/mycroft/skills.log | grep -i error | grep -i pick
03:55:04.319 - mycroft.skills.core:load_skill:166 - ERROR - Failed to load skill: pick-number.pcwii
PermissionError: [Errno 13] Permission denied: …
```
> Fix filepaths in useful diagnostic section for logs

- _pages/msk.md
- _pages/skill-settings.md
- _pages/skills-acceptance-process.md
- _pages/skills-review-code-template.md
- _pages/skills-review-functional-template.md
- _pages/skills-review-template.md
Per [this comment](https://github.com/MycroftAI/mycroft-core/pull/2113#issuecomment-491708908) from @forslund, documenting yaml as the preferred format for the settingsmeta file. If this is approved, I'll go ahead and update [mycroft-skills-kit](https://github.com/MycroftAI/mycroft-skills-kit/blob/d98b6fc18081d25c3903951e57bdb0ffc84da3f1/msk/actions/create.py#L81-L120) as well.
> Document settingsmeta.yaml

- _pages/introduction-developing-skills.md
See https://github.com/MycroftAI/mycroft-skills/commit/da6066e97e019f281d5096f33508ea8ee3208929#diff-bbacc29aecae5c3e37042cf23b14652e
> Remove references to code that's been removed

- docs/skill-development/introduction.md
- docs/skill-development/your-first-skill.md
Large rewrite of the Intro to Skill Development and Your First Skill pages to reflect the latest suggested practices when developing Skills. Strongly encourage people to use `MSK create` rather than forking the template skill.
> Update skill development intro with latest practices

- docs/using-mycroft-ai/get-mycroft/linux.md
Documentation contains a disclaimer regarding mycroft-core's default
git branch, along with instructions for switching branches from dev to
master before cloning the repo from GitHub.
dev_setup.sh now asks the user directly whether to track dev.
> Remove disclaimer re: git branch

- docs/using-mycroft-ai/get-mycroft/picroft.md
It edits local settings instead, making it useless for this specific troubleshooting case
> Don't recommend mycroft-config for global settings

- docs/skill-development/skill-settings.md
WARNING  |  8124 | mycroft.skills.settings:_update_settings_meta:310 | DEPRECATION WARNING: The "name" attribute in the settingsmeta file is no longer supported.
> Remove deprecated field from documentation

- docs/skill-development/skill-structure/skill-settings.md
The settings.json file is no longer stored in the Skill root directory
> Where to find settings.json

- docs/mycroft-technologies/mycroft-core/message-bus.md
An example that describes how exactly one should use the message bus was missing in my view. It is not exactly clear to me what xxx.yyy.zzz stand for still.
> Add example how to generate a message

- docs/using-mycroft-ai/troubleshooting/audio-troubleshooting.md
When trying to load `echo-cancellation` module, `pactl` returns and error because the module doesn't exist.
```
$ pactl load-module echo-cancellation
Failure: Module initialization failed
```
The correct module name is `module-echo-cancel`:
```
$ pactl load-module module-echo-cancel
20
```
> PulseAudio echo-cancellation module doesn't exist

- docs/using-mycroft-ai/basic-commands.md
Issue #141 - Extend list of basic voice commands available.  Edited basic-commands.md to include all 20.8 core and common Skills, except for Installer, which already has its own documentation page.  Expanded most Skills to include sample Utterances for **each** Intent, and organized the samples by intent.  Included a brief description of the Skill, and in most cases of the Intent too.
Note: The very first edit, which removes the double asterisks, looks like a violation of the style guides but in fact makes the document follow the guide - because the double asterisks are not recognized when in a description.
The use of < br > eliminated the blank phrase lines thus producing a more compact set of phrases.
Testing would require someone to try the various phrases and see if they work.  Some …
> Issue-141 - Extend list of basic voice commands available.  

- docs/using-mycroft-ai/customizations/tts-engine.md
The existing chapter in TTS documentation about Mozilla TTS server isn't very detailed and actual. Additionally the repo is now maintained by coqui. So i've added some details on installing coqui TTS server.
- [ X] Documentation improvements
Check if my described steps on setting up TTS server are working correctly.
Updated existing documentation in TTS chapter.
Already agreed in the past.
> Added details on Coqui/Mozilla TTS usage

- docs/about-mycroft-ai/contributing.md
- fixes broken link to documentation of how to ssh to Mark 1
- switch http -> https on a github website link
Fixes 2 links in documentation
> Documentation: fix 1 broken link, adjust 1 github link use https

- docs/using-mycroft-ai/customizations/tts-engine.md
The module appends `/api/tts`, so users should not provide this string or it won't work, see
https://github.com/MycroftAI/mycroft-core/blob/a487f66958b759342d055e3f61add6dd594be485/mycroft/tts/mozilla_tts.py#L30
Under each heading below is a short outline of the information required. When submitting a PR, please delete this text and replace it with your own. 
Please start with one or two sentence description of what this pull request does. 
Eg “fixes #{issue number}” or “Adds {feature} to {component}”
If needed follow up with as much detail as required.
If your PR fits more than one category, there is a high chance you should submit more than one PR. Please consider this carefully before opening the PR.
_Either delete those that do not apply, or add an x between the square brackets like …
> tts/mozila: fix wrong api path
